### ISSUE TITLE
Media handler for intake and object store dict merge is incorrect

### ISSUE THREAD

**Issue by agstephens** [cedadev/asset-generator#29]
We need to fix this. In the DKRZ instance, we have seen that all records were getting the same `properties`. We found that commenting out this line fixed the problem:

https://github.com/cedadev/asset-generator/blob/ddc8f4d1e9a552e37526446826bc2405e1396bee/asset_generator/core/asset_extractor.py#L140

So, we need to fix this:
- [ ] Create a unit test for the object store media type to scan 2 records/URLs
- [ ] Assert that they have different content matching their URLs
- [x] Fix the `asset-generator` code so that is doing that right thing at all stages

**Comment by Mahir-Sparkess** [comment]
https://github.com/cedadev/asset-generator/pull/30
